export const KEYBOARD_KEYS_ONE = [
  { id: "Esc" },
  { id: "F1", style: "space" },
  { id: "F2" },
  { id: "F3" },
  { id: "F4" },
  { id: "F5", style: "space" },
  { id: "F6" },
  { id: "F7" },
  { id: "F8" },
  { id: "F9", style: "space" },
  { id: "F0" },
  { id: "F11" },
  { id: "F12" },
];

export const KEYBOARD_KEYS_TWO = [
  { id: "`" },
  { id: "1" },
  { id: "2" },
  { id: "3" },
  { id: "4" },
  { id: "5" },
  { id: "6" },
  { id: "7" },
  { id: "8" },
  { id: "9" },
  { id: "0" },
  { id: "-" },
  { id: "=" },
  { id: "BackSpace" },
];

export const KEYBOARD_KEYS_THREE = [
  { id: "Tab" },
  { id: "q" },
  { id: "w" },
  { id: "e" },
  { id: "r" },
  { id: "t" },
  { id: "y" },
  { id: "u" },
  { id: "i" },
  { id: "o" },
  { id: "p" },
  { id: "[" },
  { id: "]" },
  { id: "Enter", style: "btnEnter" },
];

export const KEYBOARD_KEYS_FOUR = [
  { id: "CapsLock" },
  { id: "a" },
  { id: "s" },
  { id: "d" },
  { id: "f" },
  { id: "g" },
  { id: "h" },
  { id: "j" },
  { id: "k" },
  { id: "l" },
  { id: ";" },
  { id: "'" },
  { id: "\\" },
];

export const KEYBOARD_KEYS_FIVE = [
  { id: "Shift Left" },
  { id: "z" },
  { id: "x" },
  { id: "c" },
  { id: "v" },
  { id: "b" },
  { id: "n" },
  { id: "m" },
  { id: "," },
  { id: "." },
  { id: "/" },
  { id: "Shift Right" },
];

export const KEYBOARD_KEYS_SIX = [
  { id: "Ctrl Left" },
  { id: "Menu" },
  { id: "Alt Left" },
  { id: "Space", style: "spaceBtn" },
  { id: "Alt Right" },
  { id: "FN" },
  { id: "Ctrl Right" },
];

export const KEYBOARD_KEYS_SEVEN = [
  { id: "Art Scrn", style: "fontBasic" },
  { id: "Scr Lock", style: "fontBasic" },
  { id: "Pause", style: "fontBasic" },
  { id: "Ins", style: "fontBasic" },
  { id: "Home", style: "fontBasic" },
  { id: "Page Up", style: "fontBasic" },
  { id: "Del", style: "fontBasic" },
  { id: "End", style: "fontBasic" },
  { id: "Page Down", style: "fontBasic" },
  { id: "none-1", style: "btnNone fontBasic" },
  { id: "none-2", style: "btnNone fontBasic" },
  { id: "none-3", style: "btnNone fontBasic" },
  { id: "none-4", style: "btnNone fontBasic" },
  { id: `\u2191`, style: "fontBasic fontBasicSize" },
  { id: "none-5", style: "btnNone fontBasic" },
  { id: "\u2190", style: "fontBasic fontBasicSize" },
  { id: "\u2193", style: "fontBasic fontBasicSize" },
  { id: "\u2192", style: "fontBasic fontBasicSize" },
];
